// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    parent_id
) VALUES ($1, $2)
RETURNING id, name, parent_id, version, created_at, updated_at
`

type CreateCategoryParams struct {
	Name     string
	ParentID sql.NullInt32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, deleteCategory, id)
	err := row.Scan(&id)
	return id, err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT count(*) OVER() AS total_count,
    id,
    name,
    parent_id,
    version,
    created_at,
    updated_at
FROM categories
WHERE ($1 = '' OR to_tsvector('simple', name) @@ plainto_tsquery('simple', $1))
ORDER BY name
LIMIT $2 OFFSET $3
`

type GetAllCategoriesParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type GetAllCategoriesRow struct {
	TotalCount int64
	ID         int32
	Name       string
	ParentID   sql.NullInt32
	Version    int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetAllCategories(ctx context.Context, arg GetAllCategoriesParams) ([]GetAllCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoriesRow
	for rows.Next() {
		var i GetAllCategoriesRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryAveragePrice = `-- name: GetCategoryAveragePrice :one
WITH RECURSIVE category_tree AS (
    -- Base case: start with the given category
    SELECT c.id FROM categories c WHERE c.id = $1
    
    UNION ALL
    
    -- Recursive case: get all child categories
    SELECT c.id
    FROM categories c
    INNER JOIN category_tree ct ON c.parent_id = ct.id
)
SELECT 
    COALESCE(AVG(p.price_kes), 0)::text as average_price,
    COUNT(p.id) as product_count
FROM category_tree ct
LEFT JOIN products p ON p.category_id = ct.id
`

type GetCategoryAveragePriceRow struct {
	AveragePrice string
	ProductCount int64
}

func (q *Queries) GetCategoryAveragePrice(ctx context.Context, id int32) (GetCategoryAveragePriceRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryAveragePrice, id)
	var i GetCategoryAveragePriceRow
	err := row.Scan(&i.AveragePrice, &i.ProductCount)
	return i, err
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT
    id,
    name,
    parent_id,
    version,
    created_at,
    updated_at
FROM categories
WHERE id = $1 AND version = $2
`

type GetCategoryByIdParams struct {
	ID      int32
	Version int32
}

func (q *Queries) GetCategoryById(ctx context.Context, arg GetCategoryByIdParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryById, arg.ID, arg.Version)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = $2,
    parent_id = $3,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND version = $4
RETURNING name, parent_id, version, updated_at
`

type UpdateCategoryParams struct {
	ID       int32
	Name     string
	ParentID sql.NullInt32
	Version  int32
}

type UpdateCategoryRow struct {
	Name      string
	ParentID  sql.NullInt32
	Version   int32
	UpdatedAt time.Time
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Version,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.Name,
		&i.ParentID,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
