// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int32
	Name      string
	ParentID  sql.NullInt32
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Order struct {
	ID        int32
	UserID    int32
	TotalKes  string
	Status    string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrderItem struct {
	ID           int32
	OrderID      int32
	ProductID    int32
	Quantity     int32
	UnitPriceKes string
	CreatedAt    time.Time
}

type Permission struct {
	ID   int64
	Code string
}

type Product struct {
	ID            int32
	Name          string
	PriceKes      string
	CategoryID    int32
	Description   sql.NullString
	StockQuantity int32
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Token struct {
	Hash   []byte
	UserID int64
	Expiry time.Time
	Scope  string
}

type User struct {
	ID               int64
	FirstName        string
	LastName         string
	Email            string
	ProfileAvatarUrl string
	Password         []byte
	OidcSub          string
	RoleLevel        string
	Activated        bool
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LastLogin        time.Time
}

type UsersPermission struct {
	UserID       int64
	PermissionID int64
}
