// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_queries.sql

package database

import (
	"context"
	"time"
)

const createNewUser = `-- name: CreateNewUser :one
INSERT INTO users (
    first_name,
    last_name,
    email,
    profile_avatar_url,
    password,
    oidc_sub
) VALUES ($1, $2, $3, $4, $5, $6)
 RETURNING id, role_level,activated, version, created_at, updated_at, last_login
`

type CreateNewUserParams struct {
	FirstName        string
	LastName         string
	Email            string
	ProfileAvatarUrl string
	Password         []byte
	OidcSub          string
}

type CreateNewUserRow struct {
	ID        int64
	RoleLevel string
	Activated bool
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
	LastLogin time.Time
}

func (q *Queries) CreateNewUser(ctx context.Context, arg CreateNewUserParams) (CreateNewUserRow, error) {
	row := q.db.QueryRowContext(ctx, createNewUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ProfileAvatarUrl,
		arg.Password,
		arg.OidcSub,
	)
	var i CreateNewUserRow
	err := row.Scan(
		&i.ID,
		&i.RoleLevel,
		&i.Activated,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    first_name,
    last_name,
    email,
    profile_avatar_url,
    password,
    oidc_sub,
    role_level,
    activated,
    version,
    created_at,
    updated_at,
    last_login
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ProfileAvatarUrl,
		&i.Password,
		&i.OidcSub,
		&i.RoleLevel,
		&i.Activated,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = $1,
    last_name = $2,
    email = $3,
    profile_avatar_url = $4,
    password = $5,
    role_level = $6,
    activated = $7,
    version = version + 1,
    updated_at = NOW(),
    last_login = $8
WHERE id = $9 AND version = $10
RETURNING updated_at, version
`

type UpdateUserParams struct {
	FirstName        string
	LastName         string
	Email            string
	ProfileAvatarUrl string
	Password         []byte
	RoleLevel        string
	Activated        bool
	LastLogin        time.Time
	ID               int64
	Version          int32
}

type UpdateUserRow struct {
	UpdatedAt time.Time
	Version   int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ProfileAvatarUrl,
		arg.Password,
		arg.RoleLevel,
		arg.Activated,
		arg.LastLogin,
		arg.ID,
		arg.Version,
	)
	var i UpdateUserRow
	err := row.Scan(&i.UpdatedAt, &i.Version)
	return i, err
}
