apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "savannacart.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savannacart.labels" . | nindent 4 }}
data:
  # Application configuration matching the expected environment variables
  SAVANNACART_API_NAME: {{ .Values.app.name | quote }}
  SAVANNACART_API_AUTHOR: {{ .Values.app.author | quote }}
  ENV: {{ .Values.app.environment | quote }}
  
  # Database configuration (non-sensitive)
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_SSLMODE: {{ .Values.env.DB_SSLMODE | quote }}
  
  # CORS configuration
  SAVANNACART_CORS_TRUSTED_ORIGINS: {{ .Values.env.CORS_TRUSTED_ORIGINS | quote }}
  
  # Rate limiting
  RATE_LIMIT_RPS: {{ .Values.env.RATE_LIMIT_RPS | quote }}
  RATE_LIMIT_BURST: {{ .Values.env.RATE_LIMIT_BURST | quote }}
  RATE_LIMIT_ENABLED: {{ .Values.env.RATE_LIMIT_ENABLED | quote }}
