{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "savannacart.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savannacart.labels" . | nindent 4 }}
spec:
  encryptedData:
    # These values should be encrypted using kubeseal
    # To encrypt: echo -n "your-secret-value" | kubeseal --raw --from-file=/dev/stdin --namespace={{ .Release.Namespace }} --name={{ include "savannacart.fullname" . }}-secrets
    db-user: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    db-password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    oidc-client-id: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    oidc-client-secret: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    smtp-host: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    smtp-username: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    smtp-password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    smtp-sender: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    sms-account-sid: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    sms-auth-token: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
    sms-from-number: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAM...  # Replace with encrypted value
  template:
    metadata:
      name: {{ include "savannacart.fullname" . }}-secrets
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "savannacart.labels" . | nindent 8 }}
    type: Opaque
{{- else }}
# If sealed secrets are disabled, use regular Kubernetes secrets (NOT RECOMMENDED for production)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "savannacart.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savannacart.labels" . | nindent 4 }}
type: Opaque
data:
  # These are base64 encoded values - NOT SECURE for production
  db-user: {{ .Values.secrets.dbUser | b64enc }}
  db-password: {{ .Values.secrets.dbPassword | b64enc }}
  oidc-client-id: {{ .Values.secrets.oidcClientId | b64enc }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | b64enc }}
  smtp-host: {{ .Values.secrets.smtpHost | b64enc }}
  smtp-username: {{ .Values.secrets.smtpUsername | b64enc }}
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc }}
  smtp-sender: {{ .Values.secrets.smtpSender | b64enc }}
  sms-account-sid: {{ .Values.secrets.smsAccountSid | b64enc }}
  sms-auth-token: {{ .Values.secrets.smsAuthToken | b64enc }}
  sms-from-number: {{ .Values.secrets.smsFromNumber | b64enc }}
{{- end }}
